version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tap
    versions:
    - 14.11.0
    - 15.0.2
  - dependency-name: y18n
    versions:
    - 4.0.1
